name: analyze test

on: [push]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: setup
              run: yarn install --immutable
            - name: lint
              run: yarn lint
            - name: solhint
              run: yarn solhint:check
            - name: prettier
              run: yarn prettier:check
