name: hardhat test

on: [push]

jobs:
    contract-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: setup
              run: yarn
            - name: integration_test
              run: yarn test
