name: Test

on: [pull_request]

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml

  contract-test:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: integration_test
        run: yarn workspace contract test
